src/Entity/Profile.php
<?php

namespace App\Entity;

use App\Repository\ProfileRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Entity\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ProfileRepository::class)
 */
class Profile
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $role;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $quotation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $profile_img;

    /**
     * @ORM\OneToMany(targetEntity=Component::class, mappedBy="profile")
     */
    private $components;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cvlink;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cv;


    public function __construct()
    {
        $this->components = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getQuotation(): ?string
    {
        return $this->quotation;
    }

    public function setQuotation(?string $quotation): self
    {
        $this->quotation = $quotation;

        return $this;
    }

    public function getProfileImg(): ?string
    {
        return $this->profile_img;
    }

    public function setProfileImg(string $profile_img): self
    {
        $this->profile_img = $profile_img;

        return $this;
    }

    /**
     * @return Collection|Component[]
     */
    public function getComponents(): Collection
    {
        return $this->components;
    }

    public function addComponent(Component $component): self
    {
        if (!$this->components->contains($component)) {
            $this->components[] = $component;
            $component->setProfile($this);
        }

        return $this;
    }

    public function removeComponent(Component $component): self
    {
        if ($this->components->contains($component)) {
            $this->components->removeElement($component);
            // set the owning side to null (unless already changed)
            if ($component->getProfile() === $this) {
                $component->setProfile(null);
            }
        }

        return $this;
    }

    public function getCvlink(): ?string
    {
        return $this->cvlink;
    }

    public function setCvlink(?string $cvlink): self
    {
        $this->cvlink = $cvlink;

        return $this;
    }

    public function getCv(): ?string
    {
        return $this->cv;
    }

    public function setCv(?string $cv): self
    {
        $this->cv = $cv;

        return $this;
    }
}

src/Controller/Admin/HomeController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Component;
use App\Entity\Field;
use App\Entity\Profile;
use App\Entity\Type;
use App\Service\FileUploader;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/admin", name="admin")
     * @return Response
     */
    public function index()
    {

        $profile = $this->getDoctrine()->getRepository('App:Profile')->find(1) ?? new Profile();
        $types = $this->getDoctrine()->getRepository('App:Type')->findAll();

        return $this->render('admin/index.html.twig', [
            'profile' => $profile,
            'component' => $profile->getComponents(),
            'types' => $types,
        ]);
    }

    /**
     * @Route("/admin/manage/{slug}", name="admin_manage")
     * @param string $slug
     * @return Response
     */
    public function manageEntities(string $slug = 'Components')
    {
        $entity = $this->getDoctrine()->getRepository('App:'. ucfirst(substr($slug,0,-1)))->findAll();

        return $this->render('admin/manage.html.twig', [
            'types' => $this->getDoctrine()->getRepository('App:Type')->findAll(),
            'table_data' => $entity,
            'slug' => $slug
        ]);
    }

    /**
     * @Route("/admin/ajax/edit/{type}/{id}", name="admin_edit")
     * @param Request $request
     * @param string $type
     * @param int $id
     * @return Response|void
     */
    public function editEntity(Request $request, string $type, int $id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entity = $entityManager->getRepository('App:' . $type)->findOneBy(['id' => $id]);
        $types = $entityManager->getRepository('App:Type')->findAll();

        return $this->render('admin/edit.html.twig', [
                'slug' => lcfirst($type . 's'),
                'types' => $types,
                'object' => $entity,
                'action' => 'update'
        ]
        );
    }

}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        $doctrine = $this->getDoctrine();
        $profile = $doctrine->getRepository('App:Profile')->find(1);

        return $this->render('home/index.html.twig', [
            'profile' => $profile,
        ]);
    }

    /**
     * @Route("/projects", name="home_projects")
     */
    public function projects()
    {
        $doctrine = $this->getDoctrine();
        $profile = $doctrine->getRepository('App:Profile')->find(1);

        return $this->render('home/index.html.twig', [
            'profile' => $profile,
            'asd' => ''
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<header class="bounce animated" style="height: 500px;padding:100px 0;">
        <div class="container text-center justify-content-sm-center align-items-sm-center container-space-elements align-self-center d-flex">
            <div>
                <!-- Start: Avatar -->
                <div class="avatar" style="margin:0 auto;"><img src="{{ profile.profileImg }}"></div>
                <!-- End: Avatar -->
                <h1 style="font-family: 'Archivo Black', sans-serif;font-size:35px;margin-top:25px;">{{ profile.name }}</h1>
                <h4 class="text-uppercase" style="font-size: 13px;font-weight: 800;letter-spacing: 1.2px;">{{ profile.role }}</h4>
                <p class="aboutme"><cite>{{ profile.quotation }}</cite></p>
            </div>
        </div>
    </header>
    <!-- Start: Header -->
    <div class="container">
        <div class="row">
            <div class="col">
                <ul class="list-group list-group-horizontal text-monospace tab">
                    <li class="list-group-item active tab-button"><a href="{{ path('home') }}"><span>Resume</span></a></li>
                    <li class="list-group-item"><a href="{{ path('home_projects') }}"><span>Projects</span></a></li>
                </ul>
            </div>
            <div class="col text-right align-self-center">
                {% if app.user %}<button class="btn btn-link downloadbtn" type="button"><a  href="{{ path('admin') }}">Edit profile</a></button>{% endif %}
                <button class="btn btn-primary text-monospace downloadbtn" type="button"><a href="{{ profile.cv }}" style="color:white">Download Resume</a></button></div>
        </div>
    </div>
    <!-- End: Header -->
    <div class="container content">
        {% if asd is defined %}
            {%for component in profile.components|sort((a, b) => a.position <=> b.position) %}
                {% if component.location == "both sides" %}
                    {% include 'components/_projects.html.twig' with {'component': component, 'asd': asd} %}
                {% endif %}
            {% endfor %}
        {% else %}

        <div class="row row-cols-2 row-cols-sm-1 row-cols-md-1 row-cols-lg-2 row-cols-xl-2">
            <div class="col">
                <div class="row row-cols-1">
                    {%for component in profile.components|sort((a, b) => a.position <=> b.position)  %}
                        {% if component.location == "left" %}
                            {% include 'components/_' ~ component.type.name ~ '.html.twig' with {'component': component} %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

            <div class="col">
                <div class="row row-cols-1">
                    {%for component in profile.components|sort((a, b) => a.position <=> b.position) %}
                        {% if component.location == "right" %}
                            {% include 'components/_' ~ component.type.name ~ '.html.twig' with {'component': component} %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
            {%for component in profile.components|sort((a, b) => a.position <=> b.position) %}
                {% if component.location == "both sides" %}
                    {% include 'components/_' ~ component.type.name ~ '.html.twig' with {'component': component} %}
                {% endif %}
            {% endfor %}
            </div>

        {% endif %}

    <footer class="text-center" style="padding-bottom: 3%;"><button class="btn btn-primary text-monospace go-top buttoncolor" type="button">Back to top</button></footer>
</body>


</html>
{% endblock %}